[[pages]]
path = "main.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/chat.py"
name = "Chat"
icon = "ğŸ’¬"

[[pages]]
path = "pages/prompt.py"
name = "Prompt"
icon = "ğŸŒŸ"

[[pages]]
path = "pages/information.py"
name = "Information"
icon = "ğŸ“œ"

[[pages]]
path = "pages/visualization.py"
name = "Visualization"
icon = "ğŸ“Š"
